### ISSUE TITLE
Selector wrong in 7.12

### ISSUE THREAD

**Issue by nul800sebastiaan** [nathanwoulfe/NestingContently#1]
We changed this selector in 7.12.1: https://github.com/nathanwoulfe/NestingContently/blob/3004073c44255f4873799400276538733ad41441/src/NestingContently/backoffice/interceptor.js#L9

I would propose the following change to make it work for both the package version of NC and the core one:

```
const pkgStr = '<a class="nested-content__icon nested-content__icon--delete"';
const coreStr = '<a class="umb-nested-content__icon umb-nested-content__icon--delete"';
resp.data = resp.data.replace(pkgStr, '<nc-toggle /> '+ pkgStr);
resp.data = resp.data.replace(coreStr, '<nc-toggle prefix="umb-" /> '+ coreStr);
```

I just have no idea how to make the prefix work!

**Comment by nathanwoulfe** [comment]
Sorted - v1.0.5 is building now, fixes this one. Followed your lead with passing in the prefix attribute (either 'umb-' or '', depending on the version), then banging that onto my classnames in the directive. 

Also changed up the colors for 7.12 (not sure when blue changed to green, might need to have a look into that...)
