### ISSUE TITLE
Panel is hidden when used inside DTGE

### ISSUE THREAD

**Issue by bjarnef** [nathanwoulfe/NestingContently#11]
At the moment there is a port of DTGE (Doc Type Grid Editor) to Umbraco v8: https://github.com/umco/umbraco-doc-type-grid-editor/pull/137

It seems when Nested Contently is used as datatype on a Doc Type, then is the panel collapsed/hidden.

**Without** Nested Contently datatype.

![image](https://user-images.githubusercontent.com/2919859/60956596-6e2a3500-a303-11e9-9424-44d35868eeec.png)

**With** Nested Contently datatype.

![image](https://user-images.githubusercontent.com/2919859/60956682-944fd500-a303-11e9-9f80-55aad5cae017.png)

![image](https://user-images.githubusercontent.com/2919859/60956712-a3368780-a303-11e9-97f3-6848cc14def8.png)

I guess it is an issue with one of these, where it set `display:none`:
https://github.com/nathanwoulfe/NestingContently/blob/01625ef7aad01136dfe29825fc1188c562763053/src/NestingContently/backoffice/editor.controller.js#L12

https://github.com/nathanwoulfe/NestingContently/blob/01625ef7aad01136dfe29825fc1188c562763053/src/NestingContently/backoffice/button.component.js#L51

You can try the v8 port of DTGE, e.g. til install the zip file via backoffice installer.
https://ci.appveyor.com/project/UMCO/umbraco-doc-type-grid-editor/build/artifacts

**Comment by nathanwoulfe** [comment]
Yup, will be due to how I'm hiding the editor - I haven't ever looked at this in DTGE. 

I should probably be using a selector rather than grabbing the parent element, but will probably be better off waiting for the port to finish in case things change...

**Comment by bjarnef** [comment]
@nathanwoulfe this shouldn't change unless Umbraco change it in core since it is using the `umb-tabbed-content` component.
https://github.com/umco/umbraco-doc-type-grid-editor/blob/9a13c1ae301a90eaf18592fe94797effc334c774/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.dialog.html#L92-L94

**Comment by bjarnef** [comment]
Maybe it should check if the parent element has the class `umb-nested-content-property-container` instead?

**Comment by bjarnef** [comment]
Untested, but something like this might work:

```
const propElm = findAncestor($element[0], 'umb-property');

if (propElm) {
    var parentElem = propElm.parentElement;
    if (parentElem.classList.contains('umb-nested-content-property-container')) {
        parentElem.style.display = 'none';
    }
} 
```

**Comment by bjarnef** [comment]
I also noticed this console error.

![image](https://user-images.githubusercontent.com/2919859/61034526-bf026200-a3c5-11e9-9165-37d5be7e5093.png)

wheree it seems to break here:

![image](https://user-images.githubusercontent.com/2919859/61034617-e8bb8900-a3c5-11e9-865b-35f99ebefd56.png)

I just added Nested Content to a document type where DTGE and The Grid wasn't used.
With an empty Nested Content and adding a new item, I get this console error (tested on Umbraco v8.1.0)

![image](https://user-images.githubusercontent.com/2919859/61034877-64b5d100-a3c6-11e9-986b-f57741967d90.png)

**Comment by nathanwoulfe** [comment]
Hi @bjarnef, pretty sure that error is coming from an old version of the directive - latest V8 compatible release has no reference to node.tabs since that no longer exists (it's all node.variant[n].tabs. 

Was this a fresh install or update of an old site? Possibly an incorrect version installed?

**Comment by bjarnef** [comment]
@nathanwoulfe ahh I was still using the original version 1.0.6, fixed after installing v2.0.1

And this console error `elementClass is not defined` seems to be fixes here:
https://github.com/nathanwoulfe/NestingContently/pull/10

**Comment by nathanwoulfe** [comment]
Glad to hear it. Wouldn't be surprised tho if there are other issues on 8.1. Let me know if anything pops up.

**Comment by bjarnef** [comment]
@nathanwoulfe remember to update the Umbraco package as well. Not all might use the NuGet version :)
https://our.umbraco.com/packages/backoffice-extensions/nesting-contently/
https://www.nuget.org/packages/NestingContently.Umbraco/

**Comment by nathanwoulfe** [comment]
@bjarnef done. Not going to lie, I always forget to update the package repo... Would be awesome to have that integrated with my build...
