### ISSUE TITLE
Unlist version 2.0.0 from NuGet.org

### ISSUE THREAD

**Issue by ronaldbarendse** [nathanwoulfe/NestingContently#13]
Version 2.0.0 is released to NuGet with a wrong dependency on `UmbracoCms.Core`, causing it to be installed on version 7 (e.g. when using `Update-Package`).

This is fixed in https://github.com/nathanwoulfe/NestingContently/commit/4df4734861be6f4dc5ea29551f073e1bb71d3076, so it's probably best to unlist 2.0.0 from NuGet.

**Comment by nathanwoulfe** [comment]
Absolutely, makes sense - 2.0.0 is gone.
