### ISSUE TITLE
Umbraco 8.4.0 Update causes the "power" icon to disappear

### ISSUE THREAD

**Issue by hfloyd** [nathanwoulfe/NestingContently#15]
Just updated a site to 8.4.0, and noticed that the little "power" button icon which controls the show/hide operation is now missing from Nested Content. :-(

I think this might be the set of changes which killed the button:
https://github.com/umbraco/Umbraco-CMS/commit/c20416a37492afb3d6a811f1080fcf895e2f0a46

**Comment by nathanwoulfe** [comment]
Hey Heather, this looks like a fun one - the previous Nested Content directive returned all its markup in a single view, so I was able to inject my stuff without any issues. It's now a proper AngularJs component, so there's no view file to intercept. Will need to juggle some bits to make it all play nice...

**Comment by hfloyd** [comment]
Thanks for looking at this, @nathanwoulfe . If I had any angular skills to speak of, I might have maybe figured out a fix, but I have a feeling you will have a better idea how to proceed. 🙂

**Comment by nathanwoulfe** [comment]
Right. It's working, I think the way I've made it work is pretty dirty, but it works.

https://ci.appveyor.com/project/nathanwoulfe/nestingcontently/build/artifacts has links to the latest builds, if you could please test and verify, then I'll publish if everything is working.

**Comment by hfloyd** [comment]
Wow! What a quick turnaround :-) Your 2.10-alpha works perfectly. (installed via NuGet) I incremented the ClientDependency.config and did a hard refresh int he browser.

**Comment by nathanwoulfe** [comment]
Excellent. I'll package it up and release it later today

**Comment by nathanwoulfe** [comment]
@hfloyd, it took me longer to release it than it did to fix it... v2.1.0 is on nuget now, no changes from the alpha
