### ISSUE TITLE
Update PropertyValueConverter documentation for Umbraco 8

### ISSUE THREAD

**Issue by ronaldbarendse** [nathanwoulfe/NestingContently#19]
This is the updated PVC that can be used on Umbraco 8. It's basically the same as the Umbraco 7 version (https://github.com/nathanwoulfe/NestingContently/issues/3), but without the attributes:

```c#
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Core.PropertyEditors.ValueConverters;

public class NestingContentlyValueConverter : YesNoValueConverter
{
   public override bool IsConverter(IPublishedPropertyType propertyType)
      => propertyType.EditorAlias == "NestingContently";
}
```

**Comment by nathanwoulfe** [comment]
Better late than never, right @ronaldbarendse - I've updated the readme to reflect this change.
