### ISSUE TITLE
Module 'nc.components' is not available

### ISSUE THREAD

**Issue by ronaldbarendse** [nathanwoulfe/NestingContently#27]
After installing version 3.1.2 and loading the back-office, the following error is written to the console:

```
Uncaught Error: [$injector:nomod] Module 'nc.components' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

Because the JavaScript files are now bundled using Parcel, it probably doesn't import the files in the right order and hasn't registered the `nc.components` module before trying to inject it.

**Comment by ronaldbarendse** [comment]
Just to be clear: NestingContently doesn't work because of this error (although the rest of the back-office thankfully still does) 😢

So it's probably best to merge PR #28 ASAP, update the version to 3.1.3 and tag that commit with `v3.1.3`:
https://github.com/nathanwoulfe/NestingContently/blob/a7f3eedcdf76dee7668740f77d188dd77b1cbbcf/NestingContently.Umbraco/NestingContently.Umbraco.csproj#L5

After that, version 3.1.2 should be unlisted/removed from [NuGet](https://www.nuget.org/packages/NestingContently.Umbraco/3.1.2) and [Our Umbraco](https://our.umbraco.com/packages/backoffice-extensions/nesting-contently/).

Because there are no changes to the ValueConverters package, that doesn't need the version bump and will probably be skipped when trying to push to NuGet...

**Comment by ronaldbarendse** [comment]
Or if you're really bold, merge PRs #29 and #30, fix the merge conflict (because I reformatted the `umbpack push` line in the project file in one PR and removed it in the other 😏), update the version number and release that as v3.1.3 😈

Because PR #30 also fixes this issue, PR #28 can be closed without merging 👍

**Comment by nathanwoulfe** [comment]
I'm not that bold, not tonight ☺️

Priority for tomorrow.

**Comment by ronaldbarendse** [comment]
Looks like releasing to both [Our Umbraco](https://ci.appveyor.com/project/nathanwoulfe/nestingcontently/builds/35613342#L356) and [NuGet](https://ci.appveyor.com/project/nathanwoulfe/nestingcontently/builds/35613342#L395) also works as expected 👍

You might also want to unlist 3.1.2 from NuGet, so this broken version can't be installed anymore.

**Comment by nathanwoulfe** [comment]
Silky smooth! 3.1.2 is gone now too
