### ISSUE TITLE
Missing nesting-contently.min.js after 9.0.0-rc001 install

### ISSUE THREAD

**Issue by nikcio** [nathanwoulfe/NestingContently#36]
@nathanwoulfe 

It seems that version 9.0.0-rc001 doesn't copy the ~/App_Plugins/NestingContently/backoffice/nesting-contently.min.js file into the project when the package is installed.

**Comment by nathanwoulfe** [comment]
Hey @nikcio, that's entirely a stuff up on my end 😄 

I'm right now working on multi-targeting the package since that's the easier maintenance route, should have a working nightly tonight

**Comment by nathanwoulfe** [comment]
Maybe not tonight - build is being a pig. 

I did try installing, seemed to work fine for me...

**Comment by nathanwoulfe** [comment]
@nikcio try the latest build artifact => https://github.com/nathanwoulfe/NestingContently/actions/runs/1058156496

**Comment by nikcio** [comment]
@nathanwoulfe I might be missing something but I tried to install the artifact and still see the same result:

![image](https://user-images.githubusercontent.com/24605285/126783862-9be58797-20ca-4df0-a900-a642512f6edb.png)


It only copies editor.html, styles.css and package.manifest not the nesting-contently.min.js

**Comment by nathanwoulfe** [comment]
Ah, I see - when I run the build locally it's fine, but I think the CI build overwrites itself as it rebuilds the js for 472 and 5.0, which isn't required. The JS file exists in my locally built nupkg, but it's not in the CI artifact.

I've shifted the npm install/build tasks into the CI action rather than in the csproj, which should resolve it (I think).

**Comment by nathanwoulfe** [comment]
This one should be better - no more missing JS

https://github.com/nathanwoulfe/NestingContently/actions/runs/1061482756#artifacts

**Comment by nikcio** [comment]
@nathanwoulfe Yes, I can see it's copied now. I'll go ahead and close this issue then. Great work

**Comment by nathanwoulfe** [comment]
Cool, glad to hear. Let me know if you find anything else, it should all just work in 9, but never know...
