### ISSUE TITLE
At-a-glance "disabled" visibility?

### ISSUE THREAD

**Issue by hfloyd** [nathanwoulfe/NestingContently#4]
Hi @nathanwoulfe ! Thanks for this nice package. I was wondering what you thought about making "disabled" items appear more "disabled" in the general (collapsed view) of nested content items? Like, displaying the heading greyed-out, or having an always-visible enabled/disabled icon on each item? Right now you have to hover over each item individually to see the buttons appear.

**Comment by nathanwoulfe** [comment]
Hi @hfloyd, I thought I'd done that already in #2 ... Will check it out...

**Comment by nathanwoulfe** [comment]
@hfloyd, you didn't happen to install from our.umbraco by any chance? Just realised the version there was out of date - have updated with 1.0.6, which includes the styling changes.

**Comment by hfloyd** [comment]
Ah, that would be it - I did install the package from our.umbraco.com. I will use NuGet to update it. Thanks!

**Comment by nathanwoulfe** [comment]
No worries - I'm a bit slack on updating stuff on our...
