### ISSUE TITLE
Hook into changed notification and slight css alignment - v9 and v10

### ISSUE THREAD

**Issue by martinlcp** [nathanwoulfe/NestingContently#42]
I don't know if this project has seen much love lately but could I possibly request a couple of minor changes?

1. When you press the on/off button, there's no notification that the page has changed if you navigate away.  It would cause confusion with content editors if they haven't re-published and lost the change.
2.  This picky and minor but the on/off button is vertically out of alignment with the rest of the buttons in a blocklist editor and looks a little janky.

![image](https://user-images.githubusercontent.com/883638/190670179-4da1fa1e-0aaf-42cb-b24c-6145c55a0fd4.png)

I agree this should be in the core and its a standard addition to my projects :-)

**Comment by nathanwoulfe** [comment]
Hey @martinjgriffiths!

Doesn't get much love, but hasn't really needed any... That said, I'm in the middle of an update for Umbraco 10 and 11, which resolves both those issues, and makes it all work with Block Grid. 

I'm dropping support for Nested Content in the next version, so depending on your setup it might not actually be any use.

**Comment by nathanwoulfe** [comment]
@martinjgriffiths looooong time coming, but these are both resolved in the next versions (10.0.2, 11.0.2 and 12.0.0), which will be released later today.
