### ISSUE TITLE
Toogle button doesn't show

### ISSUE THREAD

**Issue by martinbrud** [nathanwoulfe/NestingContently#44]
Hi,

I had this issue some months ago: https://our.umbraco.com/forum/using-umbraco-and-getting-started//111111-nestingcontently-works-on-dev-but-not-on-prod

Have just installed NestingContently in new, empty Umbraco 11.3.1, and it still doesn't work. This time also in DEV it doesn't work. 

```
<ItemGroup>
    <PackageReference Include="NestingContently.Umbraco" Version="11.0.1" />
    <PackageReference Include="Umbraco.Cms" Version="11.3.1" />
    <PackageReference Include="uSync" Version="11.1.0" />
  </ItemGroup>
```

Have added true/false property umbracoNaviHide on my block element items, but still the toggle doesn't appear. But the property is visible in the item when I edit it: 

![screenshot](https://user-images.githubusercontent.com/48518930/235909399-411a54e4-014f-49dd-ab9f-ac10ca682fbd.png)

**Comment by greystate** [comment]
I'm seeing the same thing today using v10.0.1 - just getting an error in the console trying to load the JS from here:

`/App_Plugins/NestingContently/backoffice/nesting-contently.min.js?d=638193917150000000`

There is no NestingContently folder in App_Plugins, but frankly, since the whole _RCL revolution_ I have no clue whether there should be or not ¯\\\_(ツ)\_/¯ ?

**Comment by greystate** [comment]
Update: Downloading the nuget package and extracting the file, and putting it in the right location _does_ make the toggle appear. It also dims the row when clicked. But after **Save and publish...** the row has been enabled again, which kind of defeats the purpose :)

**Comment by nathanwoulfe** [comment]
Hey @martinbrud and @greystate, missed this one when it was raised - looking into it now, will have a new version along shortly.

**Comment by nathanwoulfe** [comment]
Should be all good now, 10.0.2, 11.0.2 and 12.0.0 are all on Nuget.

**Comment by nathanwoulfe** [comment]
And for clarity - there's no property editor as part of the 10/11/12 versions, works instead via a directive to inject the button, and some DOM-traversal mischief to hide the umbracoNaviHide property.

**Comment by martinbrud** [comment]
Thanks!

If no editor how then to enable it for a block list property editor?

**Comment by greystate** [comment]
@martinbrud You need to add an `umbracoNaviHide` property (as a boolean/toggle) to the doctype for it to work.

**Comment by martinbrud** [comment]
I have added an `umbracoNaviHide` property, but 1) there is now toogle icon when hovering and 2) the block list item isn´t grayed out when ticking it. See attached.

From website.csproj:
```
  <ItemGroup>
    <PackageReference Include="Dawoe.OEmbedPickerPropertyEditor" Version="5.0.0" />
    <PackageReference Include="Dyfort.Umbraco.AutoImageOptimize" Version="1.0.1" />
    <PackageReference Include="NestingContently.Umbraco" Version="12.0.0" />
    <PackageReference Include="Umbraco.Cms" Version="10.0.1" />
    <PackageReference Include="uSync" Version="10.0.0" />
    <PackageReference Include="Imgix" Version="3.2.2" />
  </ItemGroup>
```


![1](https://github.com/nathanwoulfe/NestingContently/assets/48518930/a77f27b6-7dec-4aef-be88-782dcc057652)
![2](https://github.com/nathanwoulfe/NestingContently/assets/48518930/f0fb0333-cd9a-4db2-9cbb-3998c1bb6e67)

**Comment by greystate** [comment]
Just a quick observation: It looks like your `umbracoNaviHide` property sits on the Block Element itself - I just noticed the "instructions" say to add it to the Block's _Settings_ element; could you try that? Just to make sure.

**Comment by nathanwoulfe** [comment]
Should work on block content or settings in the latest version, which is 11.0.2 - csproj snippet shows 11.0.1...

**Comment by martinbrud** [comment]
@nathanwoulfe My upgraded project has version 12.0.0:

```
 <ItemGroup>
...
    <PackageReference Include="NestingContently.Umbraco" Version="12.0.0" />
...
  </ItemGroup>
```

**Comment by nathanwoulfe** [comment]
Rebuild after adding the package?

**Comment by martinbrud** [comment]
Yes, did rebuild. But then tried to install it in another project and here it works. :) 


*.csproj is here:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dawoe.OEmbedPickerPropertyEditor" Version="12.0.0" />
    <PackageReference Include="Diplo.AuditLogViewer" Version="10.0.1" />
    <PackageReference Include="NestingContently.Umbraco" Version="12.0.0" />
    <PackageReference Include="Our.Umbraco.ConditionalDisplayers" Version="3.4.0" />
    <PackageReference Include="SendGrid" Version="9.28.1" />
    <PackageReference Include="Umbraco.Cloud.Cms.PublicAccess" Version="12.0.0" />
    <PackageReference Include="Umbraco.Cloud.Identity.Cms" Version="12.0.8" />
    <PackageReference Include="Umbraco.Cloud.StorageProviders.AzureBlob" Version="12.0.0" />
    <PackageReference Include="Umbraco.Cms" Version="12.1.2" />
    <PackageReference Include="Umbraco.Deploy.Cloud" Version="12.0.1" />
    <PackageReference Include="Umbraco.Deploy.Contrib" Version="12.0.0" />
    <PackageReference Include="Umbraco.Deploy.Forms" Version="12.0.1" />
    <PackageReference Include="Umbraco.Forms" Version="12.0.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- Opt-in to app-local ICU to ensure consistent globalization APIs across different platforms -->
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.9" />
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.9" Condition="$(RuntimeIdentifier.StartsWith('linux')) or $(RuntimeIdentifier.StartsWith('win')) or ('$(RuntimeIdentifier)' == '' and !$([MSBuild]::IsOSPlatform('osx')))" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Razor files are needed for the backoffice to work correctly -->
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Remove RazorCompileOnBuild and RazorCompileOnPublish when not using ModelsMode InMemoryAuto -->
    <RazorCompileOnBuild>false</RazorCompileOnBuild>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
  </PropertyGroup>
  
</Project>
```

The project that doesn't work: 
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dawoe.OEmbedPickerPropertyEditor" Version="5.0.0" />
    <PackageReference Include="Dyfort.Umbraco.AutoImageOptimize" Version="1.0.1" />
    <PackageReference Include="NestingContently.Umbraco" Version="12.0.0" />
    <PackageReference Include="Umbraco.Cms" Version="10.0.1" />
    <PackageReference Include="uSync" Version="10.0.0" />
    <PackageReference Include="Imgix" Version="3.2.2" />
  </ItemGroup>

  <!-- Force Windows to use ICU. Otherwise Windows 10 2019H1+ will do it, but older Windows 10 and most, if not all, Windows Server editions will run NLS -->
  <ItemGroup>
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.9" />
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.9" Condition="$(RuntimeIdentifier.StartsWith('linux')) or $(RuntimeIdentifier.StartsWith('win')) or ('$(RuntimeIdentifier)' == '' and !$([MSBuild]::IsOSPlatform('osx')))" />
  </ItemGroup>


  <PropertyGroup>
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot" />
  </ItemGroup>

  <!-- Keep this as false if ModelsBuilder mode is InMemoryAuto -->
  <PropertyGroup>
    <RazorCompileOnBuild>false</RazorCompileOnBuild>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
  </PropertyGroup>
</Project>
```

**Comment by nathanwoulfe** [comment]
I think the problem here is that you have NC 12.0.0 installed into an Umbraco 10 site on net6.0. NC 12 takes a dependency on Umbraco 12 and net7.0. Try installing NC 10.0.2.

**Comment by martinbrud** [comment]
@nathanwoulfe: Thanks - it works now with version 10.0.2.
