### ISSUE TITLE
Upgrading from V8/V9

### ISSUE THREAD

**Issue by nolmsted** [nathanwoulfe/NestingContently#45]
I'm upgrading a project from Umbraco 8 and it looks like things have changed significantly for versions 10/11 - is there any way to easily update data to work with the latest version without losing the disabled status that was previous a property on the block element? I suspect not, but it's pretty disappointing if I have to find another solution because compatibility was broken.

**Comment by nathanwoulfe** [comment]
Hi @nolmsted there's no change to data between versions as the package doesn't modify/store anything - if the `umbracoNaviHide` property exists on the block, it will work in 10/11/12 (albeit with the newest version which will be available later today).

I've dropped support for Nested Content in the 10+ versions, as supporting an obsolete editor added a lot of additional complexity that I am not prepared to maintain.
