### ISSUE TITLE
Doesn't show in V10

### ISSUE THREAD

**Issue by AaronSadlerUK** [nathanwoulfe/NestingContently#46]
When I install 10.0.1 it does not show under the Data Types, I have to downgrade to 4.0.0 to get it to show.

**Comment by AaronSadlerUK** [comment]
@nathanwoulfe have you been able to take a look?

It would be great to upgrade from V4!

**Comment by nathanwoulfe** [comment]
Hey@AaronSadlerUK, I missed this one - will see if I can find some time next week.

**Comment by nathanwoulfe** [comment]
Hey @AaronSadlerUK, new version/s are on Nuget now. There's no data type in the 10/11/12 versions, all you need to do is add a property aliased `umbracoNaviHide` to the block content or settings and it should all Just Work TM.

**Comment by AaronSadlerUK** [comment]
Brilliant, thanks for the update @nathanwoulfe!
