### ISSUE TITLE
Adjust styling for Umbraco 8

### ISSUE THREAD

**Issue by bjarnef** [nathanwoulfe/NestingContently#7]
Thanks for sharing this @nathanwoulfe 

I gave it a try on Umbraco v8, where it seems to work as well.
The turquoise color for the on/off button might need some adjustments for v8 and furthermore adjust the minimum target version to 8.0.0 or higher, so it is possible to find it from backoffice package installer. I tested the package by installing the Umbraco package via en local package installer.

Due a bug with the property value converter for true/false (boolean) property in the first patch releases of Umbraco v8, you need to use a workaround like the following, when querystring nested content items.

```
var boxes = Model.Value<IEnumerable<IPublishedElement>>("boxes").Where(x => x.Value<string>("umbracoNaviHide") != "1");
```

![image](https://user-images.githubusercontent.com/2919859/60160870-9ccde900-97f6-11e9-8246-625cdf509e6d.png)

![image](https://user-images.githubusercontent.com/2919859/60161780-8032b080-97f8-11e9-9ce5-9de5c2cc4dd1.png)

It also seems to work great with nested Nested Content :wink:

![image](https://user-images.githubusercontent.com/2919859/60169503-1a99f080-9807-11e9-9c99-7e0060222042.png)

**Comment by nathanwoulfe** [comment]
@bjarnef I've done a bit of a tidy up and pushed out a v8 release (v2.0.1). Everything pretty much worked out of the box, just needed a few things tweaked.
