### ISSUE TITLE
Localize icon title tooltip

### ISSUE THREAD

**Issue by bjarnef** [nathanwoulfe/NestingContently#8]
It would be great to localize icon title tooltip here.

https://github.com/nathanwoulfe/NestingContently/blob/master/src/NestingContently/backoffice/button.directive.js#L34

and here:
https://github.com/nathanwoulfe/NestingContently/blob/master/src/NestingContently/backoffice/button.directive.js#L47

You can use the following keys for "Enable " and "Disable".

https://github.com/umbraco/Umbraco-CMS/blob/b98812b119aafa54d33edbace62bd5e387f0e6a0/src/Umbraco.Web.UI/Umbraco/config/lang/en.xml#L20

https://github.com/umbraco/Umbraco-CMS/blob/b98812b119aafa54d33edbace62bd5e387f0e6a0/src/Umbraco.Web.UI/Umbraco/config/lang/en.xml#L18

**Comment by nathanwoulfe** [comment]
Probably just me being lazy... Should have been done already!

Will make it happen.

**Comment by bjarnef** [comment]
Something like this.
```
var labels = {};

var keys = [
     "actions_enable", 
     "actions_disable"
];

localizationService.localizeMany(keys).then(function(data){

      labels.enable = data[0];
      labels.disable = data[1];

});
```

**Comment by nathanwoulfe** [comment]
Sorted. It's in v2.0.1

**Comment by bjarnef** [comment]
@nathanwoulfe great! 👍 
Can you also ensure to build an Umbraco package for this version (not all are familiar with NuGet :) )?
https://our.umbraco.com/packages/backoffice-extensions/nesting-contently/

**Comment by nathanwoulfe** [comment]
I have a bad habit of forgetting to update the package repo - everything else is automated... 🤷‍♂ 

It's up there now.

**Comment by bjarnef** [comment]
Thanks @nathanwoulfe and thanks for sharing this package 👍 
It is a great alternative now we can't have visualized to disabled items in core.
https://github.com/umbraco/Umbraco-CMS/pull/5697

Maybe one day we can unpublish and have scheduled publishing on these sub nodes aka element types. That would be awesome 🚀 
https://github.com/umbraco/Umbraco-CMS/issues/2923

We sometimes have start and end date(time) pickers to simulate a simple form of scheduled publishing. Maybe your package could take this further? What do you think?
